### PR TITLE
Norm fix and span

### LINKED ISSUE #51: error in norm-estimation script
https://github.com/UCL/STIR-GATE-Connection/blob/3fef6c42adb9e0492b87bffbdcf5c2f491f4a3f1/VoxelisedSimulation/SubScripts/EstimateGATESTIRNorm.sh#L57-L60

seems wrong on 2 levels:
- the first step should use `ones.hs`. At the moment it's "unnormalising" the `model_data` (good to compare to the measured data, but not good to get nrom factors!)
- the second step isn't necessary as we could switch the bool value. 

So I believe this should be
```sh
apply_normfactors3D $OutputFilename $factors $model_data 0 $outer_iters $eff_iters 
 ```

## Some notes:
- while digging through the code, I got confused, and "documented" what I found at https://github.com/UCL/STIR/issues/706
- it's possible that the current code wouldn't suffer from the division-by-zero mentioned in that issue, but I can't see any smart handling in `stir_math` either. I guess we just have to make sure that there are no zeroes in the estimated factors. (The estimation itself will be fine, it's passing it to `BinNormalisationFromProjData` that is the problem, is that needs the norm factors)

### PR DESCRIPTION
**Pull request by robbietuk**
Fixes #51 

`apply_normfactors3D` argument with `$model_data` was wrong, this should be `ones.hs`.

Additionally, one may want the normalisation to have some level of axial compression. Adding the script argument to define `span-#` and if not `span-1`, then use `SSRB` to compress. 

This is untested right now.

### CODE REVIEW

**Review by KrisThielemans — APPROVED** [review]
seems ok

**Comment by robbietuk** [comment]
- [x] Works with span-1

- [ ] Works with span-2

SSRB is failing becuase of `span=2`
```
apply_normfactors3D
inverting the eff_factors to get norm
Compressing axial component using SSRB with num_segments_to_combine=2

ERROR: SSRB: num_segments_to_combine (2) needs to be odd
```

**Comment by KrisThielemans** [comment]
span=2 case isn't surprising. It seems non-trivial to modify the relevant `SSRB` code. However, what would be near-trivial (?) is to modify the `SSRB` utility to accept a `--template` argument, in which case it'll simply create an output file from the template, and call `SSRB(out, in, do_norm)` similar to what happens for `zoom_image`, Or do it in STIR python (SIRF doesn't expose that functionality sadly).

**Comment by robbietuk** [comment]
I think I would prefer to edit the SSRB code in STIR to take the template. I will attempt to do this.

**Comment by robbietuk** [comment]
I have modified the script to now use the template SSRB as per the changed made by https://github.com/UCL/STIR/pull/708.

The measured data (FOV source GATE data) should be unlisted in span-1 for this (`find_ML_normfactors3D` and `apply_normfactors3D` will not work otherwise).

The template sinogram can be any SSRBable template. 

This has been tested for D690 measured data (span-1). The normalisation sinogram for a span-2 D690 scanner was created successfully.

I am not willing to allow for other SSRB methods in this script, i.e. `SSRB [-t num_tangential_poss_to_trim]  output_filename input_projdata_name [num_segments_to_combine [ num_views_to_combine [do_norm [max_in_segment_num_to_process]]]]` as I think this would over complicate the script and limits the possible span's of the resulting normalisation sinogram.

**Pull request merged**
