### PR TITLE
Input file type expansion

### PR DESCRIPTION
**Pull request by robbietuk**
This PR adds the ability to setup the simulatulation with activity and attenuation `.hv` files. These files may be XCAT, volume not creatable using STIR.

### CODE REVIEW

**Comment by robbietuk** [comment]
>I'm fairly sure that stuff like $var%%} is bash specific, in which case you'll have to change the first line of the shell script.

I thought this was shell, I think I can therefore just revert the last commit in that case.

I have `.hv` and `.bin` XCAT files, which is the main motiviation for this PR. I think that we need a converter. GATE is very sensitive to its inputs and as a result `.bin` files were not acceptable.

**Comment by robbietuk** [comment]
Found a bug with the centering of the Phantom
image

**Comment by KrisThielemans** [comment]
> I have `.hv` and `.bin` XCAT files, which is the main motiviation for this PR. I think that we need a converter. GATE is very sensitive to its inputs and as a result `.bin` files were not acceptable.

sure, I'm not disputing that. The `stir_math` lines will take care of that. https://github.com/UCL/STIR-GATE-Connection/pull/31#issuecomment-656129606

I'm only saying that there's no reason why the images would have to be called `bla.hv`. I thought that the logic could be
```
if (extension is .par)
    call generate_image
    set image_name to output of generate_image
endif
```
no further messing about with extensions needed for the input filenames

**Comment by KrisThielemans** [comment]
> found a bug with the centering of the Phantom

check your `.hv` for the XCAT file. Does it have explicit offsets? get rid of them

**Comment by robbietuk** [comment]
`list_image_info $XCAT` gives 
`Origin in mm {z,y,x}    :{0, 45, 45}`
whereas the `SourceSingleCentralVoxel.par` image gives
`Origin in mm {z,y,x}    :{0, 0, 0}`

XCAT sets an origin offset. Do you not think it would be worth incorporating an this into our centering computations?

**Comment by robbietuk** [comment]
There is no explicit offset of the origin I assume STIR compute the origin from, e.g.
```
!matrix size [1] := 141
scaling factor (mm/pixel) [1] := 3
-----first pixel offset (mm) [1] := -165
```
(141 * 3)/2 = 211.5 mm 
211.5 + (- 165) =  46.5 mm = offset + half pixel width (x)
half pixel width = 1.5 mm

I think we need to correct for this.

**Comment by robbietuk** [comment]
>I'm only saying that there's no reason why the images would have to be called bla.hv. I thought that the logic could be
if (extension is .par)
    call generate_image
    set image_name to output of generate_image
endif
no further messing about with extensions needed for the input filenames

We do some further processing to adjust the attenuation to ints and convert the headers to .h33.

In this current implementation, we could check for .par and then assume everything else is a header that STIR can read.

**Comment by KrisThielemans** [comment]
> XCAT sets an origin offset.

XCAT has no clue about offsets. It generates a binary image. Somebody else created a header. If that somebody wants to shift the body from the centre of the scanner, than changing the image offset would be the way to do it, and we'll take it into account with the current code.

If `list_image_info` reports 0,0,0, the image will be centred w.r.t. the scanner. That's what we want. If `list_image_info` is not 0,0,0, the image won't be centred, and that's also what we want!

**Comment by robbietuk** [comment]
>XCAT has no clue about offsets. It generates a binary image. Somebody else created a header. If that somebody wants to shift the body from the centre of the scanner, than changing the image offset would be the way to do it, and we'll take it into account with the current code.
If list_image_info reports 0,0,0, the image will be centred w.r.t. the scanner. That's what we want. If list_image_info is not 0,0,0, the image won't be centred, and that's also what we want!

Okay, I will correct my data.

**Comment by robbietuk** [comment]
> I didn't check this properly, but a few comments
> 
> * I'm fairly sure that stuff like `${var%%xx}` is bash specific, in which case you'll have to change the first line of the shell script
> * It seems undesirable to rely on `.hv`, as STIR can read other file formats as well. Instead, I'd check if it's a `.par` file and do something, otherwise just use the existing filename. (or even better, check if the first line contains `generate_image`)

I think it is actually `shell` https://stackoverflow.com/questions/918886/how-do-i-split-a-string-on-a-delimiter-in-bash
see "Split string based on delimiter in shell"

**Comment by KrisThielemans** [comment]
> I think it is actually `shell`

`shell` doesn't exist 😉 but I guess that poster meant "most shells". `/bin/sh` should be the Bourne shell. I tried `sh` in Ubuntu and it works, so I give in. you're right!

**Comment by robbietuk** [comment]
Okay, I messed up the git badly... I rebased onto master and then pushed... It seems to have merged all the changes from master into this branch... Is there a way to fix this? Should I revert to just after the rebase onto master and then force push to this branch?

**Comment by KrisThielemans** [comment]
rebase onto master will obviously incorporate changes of master. The diff should still only show new diffs with `master`. I'm fairly sure github sees the rebase and would show only commits w.r.t. to the `master` that you rebased from.

However, I don't see any force pushes above, so I have no idea what you actually did. Proably you did the rebase locally, then merged the remote branch here (see last commit), and then pushed. That's very undesirable of course.

If you're happy with your rebase, I'd suggest to locally get rid of your last merge (`git reset --hard HEAD^1`), see what the history looks like, and then force-push to github. Or you give up, put the new files on a new branch.

rebasing is dangerous. Use it only when you really need to. (People get hung-up on "clean" history, but it's just not how life works. if you work on things in parallel, then your git history should probably show that).

**Comment by robbietuk** [comment]
Thank you. I had to rebase because I noticed an overlap between the latest merge and this PR

**Pull request merged**
